"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

import dj_database_url

from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-your-secret-key-here")
DEBUG = os.getenv("DEBUG", "True") == "True"
allowed_hosts_str = os.getenv(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,mamasho.store,www.mamasho.store"
)
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django_browser_reload",
    "catalog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Must be after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",  # Only for development
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "catalog.context_processors.basket",
                "catalog.context_processors.seo",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        # Replace this value with your local database's connection string.
        default="sqlite:///db.sqlite3",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# The URL path where static files will be accessible
STATIC_URL = "/static/"

# Directory where Django will collect all static files for deployment
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional directories where Django should look for static files
STATICFILES_DIRS = []
_project_static = BASE_DIR / "static"
if _project_static.exists():
    STATICFILES_DIRS.append(_project_static)

# Production settings for static files (when DEBUG=False)
if not DEBUG:
    # Enable the WhiteNoise storage backend, which compresses static files
    # and renames the files with unique names for each version to support
    # long-term caching
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication redirects
LOGIN_REDIRECT_URL = "product_list"
LOGOUT_REDIRECT_URL = "product_list"

# Basket settings
BASKET_SESSION_ID = "basket"

# WayForPay payment settings
WAYFORPAY_MERCHANT_ACCOUNT = os.getenv("WAYFORPAY_MERCHANT_ACCOUNT", "")
WAYFORPAY_MERCHANT_SECRET_KEY = os.getenv("WAYFORPAY_MERCHANT_SECRET_KEY", "")
# If credentials are set, default to production mode (sandbox=False)
# Set WAYFORPAY_SANDBOX=1 in .env to use sandbox mode for testing
_sandbox_env = os.getenv("WAYFORPAY_SANDBOX", "")
if _sandbox_env:
    WAYFORPAY_SANDBOX = _sandbox_env == "1"
else:
    # If not explicitly set, use production mode if credentials are configured
    WAYFORPAY_SANDBOX = not (
        WAYFORPAY_MERCHANT_ACCOUNT and WAYFORPAY_MERCHANT_SECRET_KEY
    )

# Email settings
# Use SMTP if EMAIL_HOST_USER is set, otherwise use console backend for development
_email_backend = os.getenv("EMAIL_BACKEND")
if not _email_backend:
    # If EMAIL_HOST_USER is configured, use SMTP; otherwise use console
    if os.getenv("EMAIL_HOST_USER"):
        _email_backend = "django.core.mail.backends.smtp.EmailBackend"
    else:
        _email_backend = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = _email_backend
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@mamasho.com"
)

# Order notification email
ORDER_NOTIFICATION_EMAIL = os.getenv(
    "ORDER_NOTIFICATION_EMAIL", "kuzikbv2509@gmail.com"
)
