# Generated by Django 5.2.7 on 2025-11-14 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_created_at_alter_customer_phone_basket_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Коментар до замовлення"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адреса доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Місто"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефону повинен бути в форматі: '+380501234567' (12 цифр після +).",
                        regex="^\\+380\\d{9}$",
                    )
                ],
                verbose_name="Телефон для доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Поштовий індекс"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Область"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Загальна сума замовлення",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефону повинен бути в форматі: '+380501234567' (12 цифр після +).",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує обробки"),
                    ("processing", "В обробці"),
                    ("shipped", "Відправлено"),
                    ("delivered", "Доставлено"),
                    ("cancelled", "Скасовано"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
