# Generated by Django 5.2.7 on 2025-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата оплати"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Накладений платіж (оплата при отриманні)"),
                    ("card_online", "Онлайн оплата карткою"),
                    ("bank_transfer", "Банківський переказ"),
                ],
                default="cash_on_delivery",
                max_length=50,
                verbose_name="Спосіб оплати",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує оплати"),
                    ("paid", "Оплачено"),
                    ("failed", "Помилка оплати"),
                    ("refunded", "Повернено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус оплати",
            ),
        ),
    ]
