# Generated by Django 5.2.7 on 2025-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email для отримання повідомлень про статус замовлення",
                max_length=254,
                null=True,
                verbose_name="Email для повідомлень",
            ),
        ),
    ]
