# Generated by Django 5.2.7 on 2025-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_order_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Накладений платіж (оплата при отриманні)"),
                    ("card_online", "Онлайн оплата карткою"),
                ],
                default="cash_on_delivery",
                max_length=50,
                verbose_name="Спосіб оплати",
            ),
        ),
    ]
