# Generated by Django 5.2.7 on 2025-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("80", "80 см"),
                            ("86", "86 см"),
                            ("92", "92 см"),
                            ("98", "98 см"),
                            ("104", "104 см"),
                            ("110", "110 см"),
                            ("116", "116 см"),
                            ("122", "122 см"),
                            ("128", "128 см"),
                            ("134", "134 см"),
                            ("140", "140 см"),
                            ("146", "146 см"),
                            ("152", "152 см"),
                            ("158", "158 см"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Зріст (см)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Порядок відображення (менше = вище)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Розмір",
                "verbose_name_plural": "Розміри",
                "ordering": ["order", "value"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.size",
                verbose_name="Розміри (зріст)",
            ),
        ),
    ]
