# Generated by Django 5.2.7 on 2025-11-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_size_product_sizes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ["order", "value"],
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
            },
        ),
        migrations.AlterField(
            model_name="size",
            name="value",
            field=models.CharField(
                choices=[
                    ("74-84", "74-84 см"),
                    ("84-94", "84-94 см"),
                    ("94-104", "94-104 см"),
                    ("104-114", "104-114 см"),
                    ("114-124", "114-124 см"),
                    ("124-134", "124-134 см"),
                    ("134-144", "134-144 см"),
                    ("144-154", "144-154 см"),
                    ("154-160", "154-160 см"),
                    ("160+", "160+ см"),
                ],
                max_length=10,
                unique=True,
                verbose_name="Зріст (см)",
            ),
        ),
    ]
