# Generated by Django 5.2.7 on 2025-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_add_product_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="address",
            new_name="delivery_address",
        ),
        migrations.AddField(
            model_name="customer",
            name="delivery_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Місто"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="delivery_district",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Район"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="delivery_postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Поштовий індекс"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="delivery_region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Область"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_district",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Район"
            ),
        ),
    ]
