# Generated by Django 5.2.7 on 2025-11-27 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_rename_address_customer_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефону повинен бути в форматі: '+380501234567' (12 цифр після +).",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
    ]
